apiVersion: v1
kind: Pod
metadata:
  name: iron-foot-2
  labels: 
    app: iron-cluster
spec:
  containers:
  - name: hello-ctr
    image: scmgalaxy/nginx-devopsschoolv2
    ports:
    - containerPort: 80
