kind: PersistentVolume
apiVersion: v1
metadata:
  name: dileep-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/dileep-pv1"
