apiVersion: v1
kind: ReplicationController
metadata:
  name: dileepgs-rc
spec:
  replicas: 3   
  template:
    metadata:
      labels:
        app: dileepgs-app-world
    spec:
      containers:
      - name: dileepgs-rc-ctr
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80

