apiVersion: v1
kind: ReplicationController
metadata:
  name: danny-rc
spec:
  replicas: 2   
  template:
    metadata:
      labels:
        app: hello-danny
    spec:
      containers:
      - name: hello-danny-ctr
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
