apiVersion: v1
kind: Pod
metadata:
  name: hello-pod1
  labels: 
    app: webserver2
spec:
  containers:
  - name: hello-ctr
    image: scmgalaxy/nginx-devopsschoolv2
    ports:
    - containerPort: 80

