apiVersion: v1
kind: Pod
metadata:
  name: hello-jenikins
  namespace: abhishek
  labels:
    app: webserver2
spec:
  containers:
  - name: hello-jenks
    image: jenkins
    ports:
    - containerPort: 8080

