apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-replicas-abhi
  namespace: abhishek
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-replicas-abhi
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
