apiVersion: v1
kind: ReplicationController
metadata:
  name: hellosan-rc
spec:
  replicas: 2   
  template:
    metadata:
      labels:
        app: hellosan-world
    spec:
      containers:
      - name: hellosan-ctr
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
