apiVersion: v1
kind: Pod
metadata:
  name: day5-pod2
  labels:
    app: webserver100
spec:
  containers:
    - name: custompod
      image: scmgalaxy/nginx-devopsschoolv1
      ports:
        - containerPort: 8000

